stri = input()
new_stri = (
    stri.replace(" ", "")
    .replace("a", "1 ")
    .replace("b", "2 ")
    .replace("c", "3 ")
    .replace("d", "4 ")
    .replace("e", "5 ")
    .replace("f", "6 ")
    .replace("g", "7 ")
    .replace("h", "8 ")
    .replace("i", "9 ")
    .replace("j", "10 ")
    .replace("k", "11 ")
    .replace("l", "12 ")
    .replace("m", "13 ")
    .replace("n", "14 ")
    .replace("o", "15 ")
    .replace("p", "16 ")
    .replace("q", "17 ")
    .replace("r", "18 ")
    .replace("s", "19 ")
    .replace("t", "20 ")
    .replace("u", "21 ")
    .replace("v", "22 ")
    .replace("w", "23 ")
    .replace("x", "24 ")
    .replace("y", "25 ")
    .replace("z", "26 ")
    .replace("A", "2 ")
    .replace("B", "4 ")
    .replace("C", "6 ")
    .replace("D", "8 ")
    .replace("E", "10 ")
    .replace("F", "12 ")
    .replace("G", "14 ")
    .replace("H", "16 ")
    .replace("I", "18 ")
    .replace("J", "20 ")
    .replace("K", "22 ")
    .replace("L", "24 ")
    .replace("M", "26 ")
    .replace("N", "28 ")
    .replace("O", "30 ")
    .replace("P", "32 ")
    .replace("Q", "34 ")
    .replace("R", "36 ")
    .replace("S", "38 ")
    .replace("T", "40 ")
    .replace("U", "42 ")
    .replace("V", "44 ")
    .replace("W", "46 ")
    .replace("X", "48 ")
    .replace("Y", "50 ")
    .replace("Z", "52 ")
)
new_stri = new_stri.split()
new_sum = 0
for i in new_stri:
    new_sum = new_sum + int(i)
len_new = len(str(new_sum))
if len_new < 6:
    x = 6 - len_new
    new_sum = new_sum * (10**x)
print(new_sum)
